// Document Rendering Service
// Converts ArtifactSpecifications into actual downloadable files
// Supports: DOCX, PDF, XLSX, PPTX, CSV

import type {
  ArtifactSpecification,
  OutputFormat,
  RenderableDocument,
  BrandingConfig,
} from '@/types'
import { prepareForRendering } from './artifact-engine'

// ==================== RENDERER INTERFACE ====================

export interface RendererOutput {
  buffer: Buffer
  filename: string
  mimeType: string
  size: number
}

export interface DocumentRenderer {
  format: OutputFormat
  render(document: RenderableDocument): Promise<RendererOutput>
}

// ==================== DOCX RENDERER (Real Implementation) ====================
// Uses 'docx' npm package to generate actual .docx files

export class DocxRenderer implements DocumentRenderer {
  readonly format: OutputFormat = 'DOCX'

  async render(document: RenderableDocument): Promise<RendererOutput> {
    const { Document, Packer, Paragraph, TextRun, HeadingLevel, AlignmentType, PageBreak, BorderStyle, Table, TableRow, TableCell, WidthType, Header, Footer, PageNumber, ImageRun } = await import('docx')
    
    const filename = `${this.sanitizeFilename(document.specification.title)}.docx`
    
    // Build document sections
    const children = this.buildDocxChildren(document)
    
    // Create the Word document
    const doc = new Document({
      creator: document.branding?.companyName || 'Filo',
      title: document.specification.title,
      description: document.specification.description,
      sections: [{
        properties: {
          page: {
            margin: {
              top: 1440,    // 1 inch in twips
              right: 1440,
              bottom: 1440,
              left: 1440,
            },
          },
        },
        headers: document.specification.design.layout.headerEnabled ? {
          default: new Header({
            children: [
              new Paragraph({
                alignment: AlignmentType.RIGHT,
                children: [
                  new TextRun({
                    text: document.branding?.companyName || document.specification.title,
                    size: 20,
                    color: '666666',
                    italics: true,
                  }),
                ],
              }),
            ],
          }),
        } : undefined,
        footers: document.specification.design.layout.footerEnabled ? {
          default: new Footer({
            children: [
              new Paragraph({
                alignment: AlignmentType.CENTER,
                children: [
                  new TextRun({
                    children: [PageNumber.CURRENT],
                    size: 20,
                  }),
                  new TextRun({
                    text: ` | ${document.branding?.footerText || 'Generated by Filo'}`,
                    size: 20,
                    color: '666666',
                  }),
                ],
              }),
            ],
          }),
        } : undefined,
        children,
      }],
    })

    // Generate the buffer
    const buffer = await Packer.toBuffer(doc)

    return {
      buffer,
      filename,
      mimeType: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
      size: buffer.length,
    }
  }

  private buildDocxChildren(document: RenderableDocument) {
    const children: any[] = []

    for (const section of document.sections) {
      // Add section title as heading
      if (section.type !== 'cover') {
        children.push(
          new Paragraph({
            heading: HeadingLevel.HEADING_1,
            spacing: { before: 400, after: 200 },
            children: [
              new TextRun({
                text: section.title,
                bold: true,
                size: 32,
                color: document.specification.design.colors?.primary || '1a1a1a',
              }),
            ],
          })
        )
      }

      // Process components
      for (const comp of section.components) {
        switch (comp.type) {
          case 'PARAGRAPH':
          case 'text':
            const paraContent = typeof comp.content === 'string' 
              ? comp.content 
              : JSON.stringify(comp.content)
            children.push(
              new Paragraph({
                spacing: { after: 200 },
                children: [
                  new TextRun({
                    text: paraContent,
                    size: 24,
                  }),
                ],
              })
            )
            break

          case 'HEADING':
          case 'heading':
            children.push(
              new Paragraph({
                heading: HeadingLevel.HEADING_2,
                spacing: { before: 300, after: 150 },
                children: [
                  new TextRun({
                    text: typeof comp.content === 'string' ? comp.content : JSON.stringify(comp.content),
                    bold: true,
                    size: 28,
                    color: document.specification.design.colors?.secondary || '333333',
                  }),
                ],
              })
            )
            break

          case 'LIST':
          case 'list':
            if (Array.isArray(comp.content)) {
              for (const item of comp.content) {
                children.push(
                  new Paragraph({
                    bullet: { level: 0 },
                    spacing: { after: 100 },
                    children: [
                      new TextRun({
                        text: typeof item === 'string' ? item : JSON.stringify(item),
                        size: 24,
                      }),
                    ],
                  })
                )
              }
            }
            break

          case 'TABLE':
          case 'table':
            if (Array.isArray(comp.content)) {
              const tableRows = comp.content.map((row, rowIndex) => {
                const cells = Array.isArray(row) ? row : [row]
                return new TableRow({
                  children: cells.map(cell => 
                    new TableCell({
                      children: [
                        new Paragraph({
                          children: [
                            new TextRun({
                              text: String(cell),
                              bold: rowIndex === 0,
                              size: 22,
                            }),
                          ],
                        }),
                      ],
                      width: {
                        size: Math.floor(9500 / Math.max(cells.length, 1)),
                        type: WidthType.DXA,
                      },
                    })
                  ),
                })
              })
              
              children.push(new Table({ rows: tableRows }))
            }
            break

          default:
            // Handle unknown types as text
            children.push(
              new Paragraph({
                spacing: { after: 100 },
                children: [
                  new TextRun({
                    text: typeof comp.content === 'string' ? comp.content : JSON.stringify(comp.content),
                    size: 24,
                  }),
                ],
              })
            )
        }
      }

      // Add page break between sections (except last)
      if (section !== document.sections[document.sections.length - 1]) {
        children.push(
          new Paragraph({ children: [new PageBreak()] })
        )
      }
    }

    return children
  }

  private sanitizeFilename(name: string): string {
    return name
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, '-')
      .replace(/^-|-$/g, '')
      .substring(0, 50)
  }
}

// ==================== PDF RENDERER (Real Implementation) ====================
// Uses 'pdfkit' to generate actual PDF files

export class PdfRenderer implements DocumentRenderer {
  readonly format: OutputFormat = 'PDF'

  async render(document: RenderableDocument): Promise<RendererOutput> {
    const PDFDocument = await import('pdfkit')
    
    const filename = `${this.sanitizeFilename(document.specification.title)}.pdf`
    
    // Create a new PDF document
    const doc = new PDFDocument.default({
      size: this.getPageSize(document.specification.design.layout.pageSize),
      margins: {
        top: 72,
        bottom: 72,
        left: 72,
        right: 72,
      },
      info: {
        Title: document.specification.title,
        Author: document.specification.metadata.author || 'Filo',
        Subject: document.specification.description,
        Creator: 'Filo AI',
      },
      bufferPages: true,
    })

    // Collect chunks for final buffer
    const chunks: Buffer[] = []
    
    doc.on('data', (chunk: Buffer) => chunks.push(chunk))
    
    // Set up fonts and colors
    const primaryColor = document.specification.design.colors?.primary || '#1a1a1a'
    const secondaryColor = document.specification.design.colors?.secondary || '#333333'
    
    let isFirstPage = true
    
    // Process each section
    for (const section of document.sections) {
      // Add new page for sections after first
      if (!isFirstPage) {
        doc.addPage()
      }
      isFirstPage = false
      
      // Section title
      if (section.type !== 'cover') {
        doc.fontSize(24)
          .fillColor(primaryColor)
          .text(section.title, { align: 'left' })
          .moveDown(0.5)
        
        // Underline
        doc.moveTo(doc.x, doc.y)
          .lineTo(doc.x + doc.page.width - 144, doc.y)
          .strokeColor(primaryColor)
          .lineWidth(1)
          .stroke()
          .moveDown(0.5)
      }
      
      // Process components
      for (const comp of section.components) {
        switch (comp.type) {
          case 'PARAGRAPH':
          case 'text':
            doc.fontSize(12)
              .fillColor('#000000')
              .text(typeof comp.content === 'string' ? comp.content : JSON.stringify(comp.content), {
                align: 'left',
                lineGap: 4,
              })
              .moveDown(0.3)
            break
            
          case 'HEADING':
          case 'heading':
            doc.fontSize(16)
              .fillColor(secondaryColor)
              .text(typeof comp.content === 'string' ? comp.content : JSON.stringify(comp.content), {
                align: 'left',
              })
              .moveDown(0.3)
            break
            
          case 'LIST':
          case 'list':
            if (Array.isArray(comp.content)) {
              for (const item of comp.content) {
                doc.fontSize(11)
                  .fillColor('#000000')
                 .text(`• ${typeof item === 'string' ? item : JSON.stringify(item)}`, {
                    indent: 20,
                    lineGap: 3,
                  })
                  .moveDown(0.2)
              }
            }
            break
            
          case 'TABLE':
          case 'table':
            if (Array.isArray(comp.content)) {
              this.renderPdfTable(doc, comp.content)
            }
            break
            
          default:
            doc.fontSize(11)
              .fillColor('#000000')
              .text(typeof comp.content === 'string' ? comp.content : JSON.stringify(comp.content))
              .moveDown(0.3)
        }
      }
      
      // Footer
      if (document.specification.design.layout.footerEnabled) {
        const footerText = document.branding?.footerText || 'Generated by Filo'
        doc.fontSize(8)
          .fillColor('#999999')
          .text(footerText, {
            align: 'center',
          })
      }
    }
    
    // Finalize the document
    doc.end()
    
    return new Promise((resolve) => {
      doc.on('end', () => {
        const buffer = Buffer.concat(chunks)
        resolve({
          buffer,
          filename,
          mimeType: 'application/pdf',
          size: buffer.length,
        })
      })
    })
  }

  private renderPdfTable(doc: any, data: any[]) {
    if (!data.length) return
    
    const tableWidth = doc.page.width - 144
    const colCount = Math.max(...data.map(row => Array.isArray(row) ? row.length : 1))
    const colWidth = tableWidth / colCount
    
    // Table header
    if (data[0]) {
      const headerRow = Array.isArray(data[0]) ? data[0] : [data[0]]
      doc.fontSize(10)
        .fillColor('#ffffff')
      
      // Draw header background
      doc.rect(doc.x, doc.y, tableWidth, 20).fill('#333333')
      
      headerRow.forEach((cell: any, i: number) => {
        doc.fillColor('#ffffff')
          .text(String(cell), doc.x + i * colWidth + 5, doc.y + 5, {
            width: colWidth - 10,
          })
      })
      doc.y += 25
    }
    
    // Table body
    doc.fontSize(9).fillColor('#000000')
    data.slice(1).forEach((row: any) => {
      const cells = Array.isArray(row) ? row : [row]
      cells.forEach((cell: any, i: number) => {
        doc.text(String(cell), doc.x + i * colWidth + 5, doc.y, {
          width: colWidth - 10,
        })
      })
      doc.y += 18
      
      // Row border
      doc.moveTo(doc.x, doc.y)
        .lineTo(doc.x + tableWidth, doc.y)
        .strokeColor('#cccccc')
        .lineWidth(0.5)
        .stroke()
    })
    
    doc.moveDown(0.5)
  }

  private getPageSize(size?: string): [number, number] {
    switch (size?.toUpperCase()) {
      case 'A4': return [595.28, 841.89]
      case 'LETTER': return [612, 792]
      case 'LEGAL': return [612, 1008]
      default: return [595.28, 841.89] // A4 default
    }
  }

  private sanitizeFilename(name: string): string {
    return name
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, '-')
      .replace(/^-|-$/g, '')
      .substring(0, 50)
  }
}

// ==================== XLSX RENDERER (Real Implementation) ====================
// Uses 'xlsx' (SheetJS) package to generate actual Excel files

export class XlsxRenderer implements DocumentRenderer {
  readonly format: OutputFormat = 'XLSX'

  async render(document: RenderableDocument): Promise<RendererOutput> {
    const XLSX = await import('xlsx')
    
    const filename = `${this.sanitizeFilename(document.specification.title)}.xlsx`
    
    // Create workbook
    const wb = XLSX.utils.book_new()
    
    // Create worksheets from sections
    for (const section of document.sections) {
      const sheetName = this.truncateSheetName(section.title)
      const wsData: any[][] = []
      
      // Extract data from components
      for (const comp of section.components) {
        switch (comp.type) {
          case 'TABLE':
          case 'table':
            if (Array.isArray(comp.content)) {
              wsData.push(...comp.content.map(row => 
                Array.isArray(row) ? row : [row]
              ))
              }
            break
            
          case 'LIST':
          case 'list':
            if (Array.isArray(comp.content)) {
              wsData.push(...comp.content.map(item => [item]))
            }
            break
            
          default:
            // Add as key-value pair
            const content = typeof comp.content === 'string' 
              ? comp.content 
              : JSON.stringify(comp.content)
            wsData.push([comp.type || 'Content', content])
        }
      }
      
      // If no data extracted, add section title
      if (wsData.length === 0) {
        wsData.push([section.title])
      }
      
      // Create worksheet
      const ws = XLSX.utils.aoa_to_sheet(wsData)
      
      // Set column widths
      if (wsData.length > 0) {
        const maxCols = Math.max(...wsData.map(row => row.length))
        ws['!cols'] = Array(maxCols).fill({ wch: 20 })
      }
      
      // Add worksheet to workbook
      XLSX.utils.book_append_sheet(wb, ws, sheetName)
    }
    
    // Generate buffer
    const buffer = XLSX.write(wb, { type: 'buffer', bookType: 'xlsx' }) as Buffer

    return {
      buffer,
      filename,
      mimeType: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
      size: buffer.length,
    }
  }

  private truncateSheetName(name: string): string {
    // Excel worksheet names max 31 chars, cannot contain: \ / ? * [ ] :
    return name
      .replace(/[\\\/\?\*\[\]:]/g, '_')
      .substring(0, 31)
      || 'Sheet1'
  }

  private sanitizeFilename(name: string): string {
    return name
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, '-')
      .replace(/^-|-$/g, '')
      .substring(0, 50)
  }
}

// ==================== PPTX RENDERER (Real Implementation) ====================
// Uses 'pptxgenjs' to generate actual PowerPoint presentations

export class PptxRenderer implements DocumentRenderer {
  readonly format: OutputFormat = 'PPTX'

  async render(document: RenderableDocument): Promise<RendererOutput> {
    const pptxgen = await import('pptxgenjs')
    
    const filename = `${this.sanitizeFilename(document.specification.title)}.pptx`
    
    // Create presentation
    const pres = new pptxgen.default()
    
    pres.author = document.specification.metadata.author || 'Filo'
    pres.title = document.specification.title
    pres.subject = document.specification.description
    pres.company = document.branding?.companyName || 'Filo'
    
    // Define layout
    pres.layout = 'LAYOUT_16x9'
    
    // Get colors from design config
    const primaryColor = document.specification.design.colors?.primary || '1E2761'
    const accentColor = document.specification.design.colors?.accent || '3B82F6'
    const bgColor = document.specification.design.colors?.background || 'FFFFFF'
    
    let slideIndex = 0
    
    // Process each section as a slide or slides
    for (const section of document.sections) {
      slideIndex++
      
      // Determine slide type based on section type
      const isCoverSlide = section.type === 'cover' || slideIndex === 1
      const isSectionDivider = section.type === 'heading' || section.type === 'section'
      
      // Create slide
      const slide = pres.addSlide()
      
      // Background
      slide.background = { color: bgColor }
      
      if (isCoverSlide) {
        // Cover/Title Slide
        this.renderCoverSlide(slide, section, document, primaryColor, accentColor)
      } else if (isSectionDivider && section.components.length <= 2) {
        // Section divider slide
        this.renderSectionSlide(slide, section, document, primaryColor, accentColor)
      } else {
        // Content slide
        this.renderContentSlide(slide, section, document, primaryColor, accentColor)
      }
    }
    
    // Generate file
    const buffer = await pres.writeFile({ outputType: 'nodebuffer' }) as Buffer

    return {
      buffer,
      filename,
      mimeType: 'application/vnd.openxmlformats-officedocument.presentationml.presentation',
      size: buffer.length,
    }
  }

  private renderCoverSlide(slide: any, section: any, document: any, primaryColor: string, accentColor: string) {
    // Title
    slide.addText(document.specification.title, {
      x: 0.5,
      y: 2.5,
      w: 9,
      h: 1.5,
      fontSize: 44,
      fontFace: 'Arial',
      color: primaryColor,
      bold: true,
      align: 'center',
    })
    
    // Subtitle/description
    if (document.specification.description) {
      slide.addText(document.specification.description, {
        x: 1,
        y: 4.2,
        w: 8,
        h: 0.8,
        fontSize: 18,
        fontFace: 'Arial',
        color: '666666',
        align: 'center',
      })
    }
    
    // Author/branding
    const author = document.specification.metadata.author || document.branding?.companyName
    if (author) {
      slide.addText(author, {
        x: 1,
        y: 5.2,
        w: 8,
        h: 0.5,
        fontSize: 14,
        fontFace: 'Arial',
        color: '888888',
        align: 'center',
      })
    }
  }

  private renderSectionSlide(slide: any, section: any, document: any, primaryColor: string, accentColor: string) {
    // Section title centered
    slide.addText(section.title, {
      x: 0.5,
      y: 2.5,
      w: 9,
      h: 1.5,
      fontSize: 36,
      fontFace: 'Arial',
      color: primaryColor,
      bold: true,
      align: 'center',
    })

    // Accent line using addShape with shapeType string
    slide.addShape('rect', {
      x: 3.5,
      y: 4.2,
      w: 3,
      h: 0.05,
      fill: { color: accentColor },
    })
  }

  private renderContentSlide(slide: any, section: any, document: any, primaryColor: string, accentColor: string) {
    // Section title at top
    slide.addText(section.title, {
      x: 0.5,
      y: 0.3,
      w: 9,
      h: 0.7,
      fontSize: 28,
      fontFace: 'Arial',
      color: primaryColor,
      bold: true,
    })
    
    // Content area
    let yPos = 1.2
    const maxWidth = 9
    const leftMargin = 0.5
    
    for (const comp of section.components) {
      switch (comp.type) {
        case 'PARAGRAPH':
        case 'text':
          const text = typeof comp.content === 'string' ? comp.content : JSON.stringify(comp.content)
          slide.addText(text, {
            x: leftMargin,
            y: yPos,
            w: maxWidth,
            h: Math.min(text.length / 80, 2), // Auto-height estimate
            fontSize: 14,
            fontFace: 'Arial',
            color: '333333',
            valign: 'top',
          })
          yPos += Math.ceil(text.length / 80) * 0.35 + 0.2
          break
          
        case 'HEADING':
        case 'heading':
          slide.addText(typeof comp.content === 'string' ? comp.content : JSON.stringify(comp.content), {
            x: leftMargin,
            y: yPos,
            w: maxWidth,
            h: 0.5,
            fontSize: 18,
            fontFace: 'Arial',
            color: primaryColor,
            bold: true,
          })
          yPos += 0.7
          break
          
        case 'LIST':
        case 'list':
          if (Array.isArray(comp.content)) {
            for (const item of comp.content) {
              slide.addText([
                { text: '\u2022 ', options: { color: accentColor, bold: true } },
                { text: typeof item === 'string' ? item : JSON.stringify(item) },
              ], {
                x: leftMargin + 0.3,
                y: yPos,
                w: maxWidth - 0.3,
                h: 0.4,
                fontSize: 13,
                fontFace: 'Arial',
                color: '444444',
              })
              yPos += 0.4
            }
          }
          break
          
        case 'TABLE':
        case 'table':
          if (Array.isArray(comp.content) && comp.content.length > 0) {
            const tableData = comp.content.map((row: any, rowIndex) => {
              const cells = Array.isArray(row) ? row.map(String) : [String(row)]
              // Style header row differently
              if (rowIndex === 0) {
                return cells.map(cell => ({
                  text: cell,
                  options: { bold: true, color: primaryColor, fontSize: 12, fill: { color: 'F0F4FF' } }
                }))
              }
              return cells
            })
            
            slide.addTable(tableData, {
              x: leftMargin,
              y: yPos,
              w: maxWidth,
              fontSize: 11,
              fontFace: 'Arial',
              border: { pt: 0.5, color: 'CCCCCC' },
              color: '333333',
              valign: 'middle',
              align: 'left',
              autoPage: false,
            })
            
            // Estimate height based on rows
            yPos += comp.content.length * 0.4 + 0.5
          }
          break
          
        default:
          // Fallback for unknown types
          const fallbackText = typeof comp.content === 'string' ? comp.content : JSON.stringify(comp.content)
          slide.addText(fallbackText, {
            x: leftMargin,
            y: yPos,
            w: maxWidth,
            h: 0.4,
            fontSize: 12,
            fontFace: 'Arial',
            color: '666666',
          })
          yPos += 0.5
      }
      
      // Prevent overflow
      if (yPos > 5) break
    }
  }

  private sanitizeFilename(name: string): string {
    return name
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, '-')
      .replace(/^-|-$/g, '')
      .substring(0, 50)
  }
}

// ==================== CSV RENDERER (Already Working) ====================

export class CsvRenderer implements DocumentRenderer {
  readonly format: OutputFormat = 'CSV'

  async render(document: RenderableDocument): Promise<RendererOutput> {
    const csvContent = this.buildCsvContent(document)
    const filename = `${this.sanitizeFilename(document.specification.title)}.csv`

    return {
      buffer: Buffer.from(csvContent, 'utf-8'),
      filename,
      mimeType: 'text/csv',
      size: csvContent.length,
    }
  }

  private buildCsvContent(document: RenderableDocument): string {
    const rows: string[][] = []
    
    // Extract table data from all sections
    for (const section of document.sections) {
      for (const component of section.components) {
        if (component.type === 'TABLE' && Array.isArray(component.content)) {
          rows.push(...(component.content as string[][]))
        }
      }
    }

    if (rows.length === 0) {
      // Fallback: create CSV from text content
      rows.push(['Title', 'Content'])
      for (const section of document.sections) {
        const textContent = section.components
          .filter(c => c.type === 'PARAGRAPH')
          .map(c => typeof c.content === 'object' && c.content !== null && 'text' in c.content 
            ? (c.content as { text: string }).text 
            : JSON.stringify(c.content))
          .join(' ')
        rows.push([section.title, textContent])
      }
    }

    // Escape and format as CSV
    return rows.map(row =>
      row.map(cell => {
        const str = String(cell)
        if (str.includes(',') || str.includes('"') || str.includes('\n')) {
          return `"${str.replace(/"/g, '""')}"`
        }
        return str
      }).join(',')
    ).join('\n')
  }

  private sanitizeFilename(name: string): string {
    return name
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, '-')
      .replace(/^-|-$/g, '')
      .substring(0, 50)
  }
}

// ==================== TXT RENDERER ====================

export class TxtRenderer implements DocumentRenderer {
  readonly format: OutputFormat = 'TXT'

  async render(document: RenderableDocument): Promise<RendererOutput> {
    const lines: string[] = []

    // Title
    lines.push(document.specification.title)
    lines.push('='.repeat(document.specification.title.length))
    lines.push('')

    if (document.specification.description) {
      lines.push(document.specification.description)
      lines.push('')
    }

    for (const section of document.sections) {
      if (section.type !== 'cover') {
        lines.push(section.title)
        lines.push('-'.repeat(section.title.length))
        lines.push('')
      }

      for (const comp of section.components) {
        switch (comp.type) {
          case 'HEADING':
          case 'heading':
            lines.push(typeof comp.content === 'string' ? comp.content : JSON.stringify(comp.content))
            lines.push('')
            break

          case 'PARAGRAPH':
          case 'text':
            lines.push(typeof comp.content === 'string' ? comp.content : JSON.stringify(comp.content))
            lines.push('')
            break

          case 'LIST':
          case 'list':
            if (Array.isArray(comp.content)) {
              for (const item of comp.content) {
                lines.push(`  - ${typeof item === 'string' ? item : JSON.stringify(item)}`)
              }
              lines.push('')
            }
            break

          case 'TABLE':
          case 'table':
            if (Array.isArray(comp.content)) {
              for (const row of comp.content) {
                const cells = Array.isArray(row) ? row : [row]
                lines.push('  ' + cells.map(c => String(c)).join(' | '))
              }
              lines.push('')
            }
            break

          default:
            lines.push(typeof comp.content === 'string' ? comp.content : JSON.stringify(comp.content))
            lines.push('')
        }
      }
    }

    const textContent = lines.join('\n')
    const filename = `${this.sanitizeFilename(document.specification.title)}.txt`

    return {
      buffer: Buffer.from(textContent, 'utf-8'),
      filename,
      mimeType: 'text/plain',
      size: textContent.length,
    }
  }

  private sanitizeFilename(name: string): string {
    return name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '').substring(0, 50)
  }
}

// ==================== HTML RENDERER ====================

export class HtmlRenderer implements DocumentRenderer {
  readonly format: OutputFormat = 'HTML'

  async render(document: RenderableDocument): Promise<RendererOutput> {
    const primaryColor = document.specification.design.colors?.primary || '#1a1a1a'
    const accentColor = document.specification.design.colors?.accent || '#3B82F6'

    let bodyHtml = ''

    // Cover / Title section
    bodyHtml += `<div style="text-align:center; padding: 48px 0 32px;">`
    bodyHtml += `<h1 style="color:${primaryColor}; font-size:2em; margin-bottom:8px;">${this.escapeHtml(document.specification.title)}</h1>`
    if (document.specification.description) {
      bodyHtml += `<p style="color:#666; font-size:1.1em;">${this.escapeHtml(document.specification.description)}</p>`
    }
    bodyHtml += `</div>`

    for (const section of document.sections) {
      if (section.type === 'cover') continue

      bodyHtml += `<section style="margin-bottom:32px;">`
      bodyHtml += `<h2 style="color:${primaryColor}; border-bottom:2px solid ${accentColor}; padding-bottom:8px;">${this.escapeHtml(section.title)}</h2>`

      for (const comp of section.components) {
        switch (comp.type) {
          case 'HEADING':
          case 'heading':
            bodyHtml += `<h3 style="color:#333; margin:16px 0 8px;">${this.escapeHtml(String(comp.content))}</h3>`
            break

          case 'PARAGRAPH':
          case 'text':
            bodyHtml += `<p style="line-height:1.7; color:#444; margin-bottom:12px;">${this.escapeHtml(String(comp.content))}</p>`
            break

          case 'LIST':
          case 'list':
            if (Array.isArray(comp.content)) {
              bodyHtml += `<ul style="margin-bottom:12px; padding-left:24px;">`
              for (const item of comp.content) {
                bodyHtml += `<li style="line-height:1.6; margin-bottom:4px;">${this.escapeHtml(String(item))}</li>`
              }
              bodyHtml += `</ul>`
            }
            break

          case 'TABLE':
          case 'table':
            if (Array.isArray(comp.content) && comp.content.length > 0) {
              bodyHtml += `<table style="width:100%; border-collapse:collapse; margin-bottom:16px;">`
              comp.content.forEach((row: any, rowIdx: number) => {
                const cells = Array.isArray(row) ? row : [row]
                const tag = rowIdx === 0 ? 'th' : 'td'
                const bg = rowIdx === 0 ? `background:${primaryColor}; color:white;` : rowIdx % 2 === 0 ? 'background:#f8f9fa;' : ''
                bodyHtml += `<tr>`
                for (const cell of cells) {
                  bodyHtml += `<${tag} style="${bg} padding:8px 12px; border:1px solid #ddd; text-align:left;">${this.escapeHtml(String(cell))}</${tag}>`
                }
                bodyHtml += `</tr>`
              })
              bodyHtml += `</table>`
            }
            break

          default:
            bodyHtml += `<p style="line-height:1.7; color:#444; margin-bottom:12px;">${this.escapeHtml(String(comp.content))}</p>`
        }
      }

      bodyHtml += `</section>`
    }

    const fullHtml = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${this.escapeHtml(document.specification.title)}</title>
  <style>
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; max-width: 800px; margin: 0 auto; padding: 24px; color: #333; }
  </style>
</head>
<body>
${bodyHtml}
</body>
</html>`

    const filename = `${this.sanitizeFilename(document.specification.title)}.html`

    return {
      buffer: Buffer.from(fullHtml, 'utf-8'),
      filename,
      mimeType: 'text/html',
      size: fullHtml.length,
    }
  }

  private escapeHtml(text: string): string {
    return text
      .replace(/&/g, '&amp;')
      .replace(/</g, '&lt;')
      .replace(/>/g, '&gt;')
      .replace(/"/g, '&quot;')
  }

  private sanitizeFilename(name: string): string {
    return name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '').substring(0, 50)
  }
}

// ==================== RENDERER REGISTRY ====================

export const renderers: Map<OutputFormat, DocumentRenderer> = new Map([
  ['DOCX', new DocxRenderer()],
  ['PDF', new PdfRenderer()],
  ['XLSX', new XlsxRenderer()],
  ['PPTX', new PptxRenderer()],
  ['CSV', new CsvRenderer()],
  ['TXT', new TxtRenderer()],
  ['HTML', new HtmlRenderer()],
])

/**
 * Get renderer for a specific format
 */
export function getRenderer(format: OutputFormat): DocumentRenderer | undefined {
  return renderers.get(format)
}

/**
 * Render an artifact specification to the specified format
 */
export async function renderArtifact(
  specification: ArtifactSpecification,
  components: Array<{ sectionId: string; componentId: string; type: string; content: unknown; style?: Record<string, unknown>; order: number }>,
  format: OutputFormat
): Promise<RendererOutput> {
  const renderer = getRenderer(format)
  
  if (!renderer) {
    throw new Error(`No renderer available for format: ${format}`)
  }

  const document = prepareForRendering(specification, components)
  return renderer.render(document)
}

/**
 * Get supported export formats
 */
export function getSupportedFormats(): OutputFormat[] {
  return Array.from(renderers.keys())
}
